# POSTGRES
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/star-seeker
#    username: admin
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#      properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#  sql:
#    init:
#      mode: always
#jwt:
#  public:
#    key: classpath:app.pub
#  private:
#    key: classpath:app.key

spring:
  datasource:
    url: jdbc:h2:mem:starseeker
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: true

  sql:
    init:
      mode: always

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key

server:
  port: 8080
